name: Generate Random Python File

on: [workflow_dispatch]  # Allows manual triggering from GitHub UI

jobs:
  generate-file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Generate Random Python File
        run: |
          RANDOM_NAME="script_$(date +%s).py"
          echo 'print("Hello from $RANDOM_NAME")' > $RANDOM_NAME
          echo "Generated file: $RANDOM_NAME"

      - name: Commit and Push File
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add *.py
          git commit -m "Added a random Python script"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
